version: '3.8'

services:
  nostr-notification-server:
    container_name: nostr-notification-server
    build: .
    ports:
      - "3030:3030"
    volumes:
      - ./db:/app/db
      - ./config:/app/config
    environment:
      - RUST_LOG=debug
      - NNS_HTTP_PORT=3030
      - NNS_HOSTNAME=localhost
      # Optional: Override other settings
      # - NNS_DB_MAP_SIZE=1073741824
      # - NNS_RELAYS=["wss://relay.damus.io","wss://nos.lol"]
