[package]
name = "nostr-social-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
heed = "0.20.5"
serde_json = "1.0.132"
url = "2.5.3"
tokio = { version = "1.0", features = ["full"] }
nostr-sdk = "0.35"
log = "0.4"
